/**
 * QCOM Ecosystem Seed Dataset & Mock State
 * Fully compatible with QCOM Customer, Seller, and Admin specifications.
 */

import {
  DeliveryPartnerProfile,
  DeliveryTask,
  PartnerEarningsSummary,
  RiderLedgerEntry,
  PartnerNotification,
  ShiftSlot,
  KycDocumentDetail,
  VehicleConstraint,
  AssetAllocation,
  SafetyTrainingModule,
  PerformanceScorecard,
} from '../types/delivery';

export const INITIAL_PARTNER_PROFILE: DeliveryPartnerProfile = {
  id: 'RIDER-4029',
  partnerCode: 'QCOM-RD-9402',
  name: 'Vikram Singh',
  phone: '+91 98450 82190',
  maskedPhone: '+91 98XXX-XX190 (QCOM Proxy)',
  email: 'vikram.singh@qcom-delivery.in',
  photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
  cityId: 'BLR-01',
  cityName: 'Bengaluru (East Zone)',
  assignedHubName: 'Indiranagar Zone',
  vehicleType: 'EV_SCOOTER',
  vehicleModel: 'Ather 450X Gen 3 (#EV-142)',
  vehicleNumber: 'KA 03 EV 8821',
  batteryPercent: 84,
  batteryEstimatedRangeKm: 72,
  dutyStatus: 'offline',
  isOnline: false,
  rating: 4.92,
  completedDeliveriesCount: 418,
  onTimeDeliveryRatePercent: 98.4,
  acceptanceRatePercent: 96.5,
  tierLevel: 'PLATINUM',
  floatingCashBalance: 850.0,
  floatingCashLimit: 2500.0,
  bankAccount: {
    accountNumber: '9182371900128',
    accountHolderName: 'VIKRAM SINGH',
    ifscCode: 'HDFC0001892',
    bankName: 'HDFC Bank Ltd',
    upiId: 'vikram.singh@okaxis',
    isVerified: true,
  },
  documents: {
    aadhaarVerified: true,
    drivingLicenseVerified: true,
    vehicleRcVerified: true,
    insuranceVerified: true,
    bankVerified: true,
    bgvCleared: true,
  },
  currentLocation: { lat: 12.9784, lng: 77.6408 },
  joinedDate: '12 Jan 2025',
  shiftHoursTodayMinutes: 310,
};

export const INITIAL_ACTIVE_TASK: DeliveryTask = {
  id: 'TASK-9021',
  orderId: 'ORD-88192',
  orderNumber: '#Q88192',
  orderStatus: 'packed',
  placedAt: '10 mins ago',
  packedAt: '2 mins ago',
  estimatedDeliveryAt: '12 mins from now',
  items: [
    {
      productId: 'PROD-101',
      productName: 'Havells 2.5 sq mm FR PVC Copper Wire (90m, Red)',
      brand: 'Havells',
      quantity: 2,
      unit: 'Rolls',
      price: 1850,
      binLocation: 'Aisle 2 - Bin 14A',
    },
    {
      productId: 'PROD-204',
      productName: 'Schneider Electric 16A Single Pole MCB C-Curve',
      brand: 'Schneider',
      quantity: 6,
      unit: 'Pieces',
      price: 210,
      binLocation: 'Aisle 1 - Bin 08C',
    },
    {
      productId: 'PROD-309',
      productName: 'Finolex CPVC Cement Solvent 250ml',
      brand: 'Finolex',
      quantity: 1,
      unit: 'Can',
      price: 180,
      binLocation: 'Aisle 4 - Bin 02A',
    },
  ],
  itemCount: 9,
  orderTotalAmount: 5140,
  paymentMethod: 'Instant UPI',
  paymentStatus: 'PAID',
  isUrgentJobsite: true,
  pickup: {
    sellerId: 'STORE-201',
    storeName: 'Sri Lakshmi Electricals & Hardware Partner',
    hubType: 'Partner Retail Hardware Hub',
    phone: '+91 98765 43210',
    maskedPhone: '+91 98XXX-XX210 (QCOM Proxy)',
    address: '100 Feet Road, 12th Main, Indiranagar',
    locality: 'Indiranagar, Bengaluru',
    coordinates: { lat: 12.9784, lng: 77.6408 },
    accessibleEntranceCoords: { lat: 12.9786, lng: 77.6410 },
    pickupNotes: 'Enter via rear loading gate B. Order counter is on the left side near Bin Aisle 2.',
    basePrepMins: 4,
    isPacked: true,
  },
  drop: {
    customerName: 'Rahul Sharma (Site Supervisor)',
    customerPhone: '+91 98450 12891',
    maskedPhone: '+91 98XXX-XX891 (QCOM IVR Proxy)',
    isPhoneMasked: true,
    accountType: 'contractor',
    businessName: 'Apex Infra & Renovations LLP',
    address: 'Site B - Block 4, 8th Main, Koramangala 5th Block',
    locality: 'Koramangala 5th Block, Bengaluru',
    landmark: 'Opposite Sony World Signal, Behind BDA Complex',
    floorUnit: '2nd Floor, Commercial Fitting Site',
    gateCode: 'GATE-04',
    siteContactName: 'Manoj (Electrician Lead)',
    sitePhone: '+91 98112 33445',
    dropoffInstructions: 'Call site lead Manoj on arrival. Park scooter at basement entry. Elevators operational.',
    coordinates: { lat: 12.9352, lng: 77.6245 },
    accessibleEntranceCoords: { lat: 12.9354, lng: 77.6247 },
  },
  payoutBreakdown: {
    basePay: 35,
    distancePay: 28, // 3.5 km * ₹8
    transitTimePay: 6, // 12 mins * ₹0.5
    surgeBonus: 15, // Rainy / Peak Demand
    multiPickupBonus: 0,
    customerTip: 30, // Passed 100%
    totalPayout: 114,
  },
  route: {
    distanceMeters: 3850,
    distanceKm: 3.85,
    estimatedDurationMins: 11,
    formattedEta: '11 mins',
    polyline: [
      [12.9784, 77.6408],
      [12.9720, 77.6380],
      [12.9610, 77.6330],
      [12.9500, 77.6290],
      [12.9352, 77.6245],
    ],
    instructions: [
      { text: 'Head South on 100 Feet Rd toward 12th Main', distanceMeters: 600, durationSeconds: 120, location: [12.9784, 77.6408] },
      { text: 'Turn right onto Intermediate Ring Rd', distanceMeters: 1800, durationSeconds: 320, location: [12.9720, 77.6380] },
      { text: 'Slight left onto 8th Main Rd, Koramangala', distanceMeters: 1150, durationSeconds: 210, location: [12.9610, 77.6330] },
      { text: 'Arrive at Site B, Koramangala 5th Block', distanceMeters: 300, durationSeconds: 50, location: [12.9352, 77.6245] },
    ],
  },
  deliveryOtp: '4829',
};

export const UNASSIGNED_BROADCAST_TASKS: DeliveryTask[] = [
  INITIAL_ACTIVE_TASK,
  {
    id: 'TASK-9022',
    orderId: 'ORD-88193',
    orderNumber: '#Q88193',
    orderStatus: 'packed',
    placedAt: '5 mins ago',
    packedAt: '1 min ago',
    estimatedDeliveryAt: '14 mins from now',
    items: [
      { productId: 'PROD-801', productName: 'Bosch Professional 13mm Impact Drill GSB 500', brand: 'Bosch', quantity: 1, unit: 'Kit', price: 3450 },
      { productId: 'PROD-802', productName: '3M Safety Goggles & Respirator Mask Set', brand: '3M', quantity: 2, unit: 'Sets', price: 420 },
    ],
    itemCount: 3,
    orderTotalAmount: 4290,
    paymentMethod: 'Trade Credit (Net 30)',
    paymentStatus: 'PAID',
    isUrgentJobsite: true,
    pickup: {
      sellerId: 'STORE-204',
      storeName: 'Koramangala Pro Tools & Fasteners',
      hubType: 'Partner Hardware Hub',
      phone: '+91 98888 11223',
      maskedPhone: '+91 98XXX-XX223 (QCOM Proxy)',
      address: '80 Feet Road, 6th Block, Koramangala',
      locality: 'Koramangala, Bengaluru',
      coordinates: { lat: 12.9380, lng: 77.6280 },
      basePrepMins: 3,
      isPacked: true,
    },
    drop: {
      customerName: 'Anil Kumar (Civil Supervisor)',
      customerPhone: '+91 98777 66554',
      maskedPhone: '+91 98XXX-XX554 (QCOM Proxy)',
      isPhoneMasked: true,
      accountType: 'contractor',
      businessName: 'Vanguard Builders',
      address: 'Plot 42, HSR Layout Sector 1',
      locality: 'HSR Layout, Bengaluru',
      landmark: 'Near Agara Lake Junction',
      siteContactName: 'Suresh (Site Manager)',
      sitePhone: '+91 98123 99887',
      coordinates: { lat: 12.9121, lng: 77.6446 },
    },
    payoutBreakdown: {
      basePay: 35,
      distancePay: 22,
      transitTimePay: 5,
      surgeBonus: 15,
      multiPickupBonus: 0,
      customerTip: 20,
      totalPayout: 97,
    },
    route: {
      distanceMeters: 2800,
      distanceKm: 2.8,
      estimatedDurationMins: 9,
      formattedEta: '9 mins',
      polyline: [
        [12.9380, 77.6280],
        [12.9250, 77.6350],
        [12.9121, 77.6446],
      ],
      instructions: [
        { text: 'Head South toward 100 Feet Rd', distanceMeters: 1200, durationSeconds: 200, location: [12.9380, 77.6280] },
        { text: 'Turn left toward Agara Lake', distanceMeters: 1600, durationSeconds: 280, location: [12.9121, 77.6446] },
      ],
    },
    deliveryOtp: '7193',
  },
];

export const INITIAL_COMPLETED_TASKS: DeliveryTask[] = [
  {
    id: 'TASK-9019',
    orderId: 'ORD-88191',
    orderNumber: '#Q88191',
    orderStatus: 'delivered',
    placedAt: '2026-09-22T08:15:00.000Z',
    packedAt: '2026-09-22T08:25:00.000Z',
    assignedAt: '2026-09-22T08:26:00.000Z',
    acceptedAt: '2026-09-22T08:26:30.000Z',
    pickedUpAt: '2026-09-22T08:35:00.000Z',
    deliveredAt: '2026-09-22T08:52:00.000Z',
    estimatedDeliveryAt: '2026-09-22T08:55:00.000Z',
    items: [
      {
        productId: 'P-101',
        productName: 'Heavy-Duty 1.5 sq mm FR Copper Wire 90m (Red)',
        brand: 'Havells',
        quantity: 2,
        unit: 'Coils',
        price: 1850,
      },
    ],
    itemCount: 2,
    orderTotalAmount: 3700,
    paymentMethod: 'Instant UPI',
    paymentStatus: 'PAID',
    pickup: {
      sellerId: 'SEL-8819',
      storeName: 'Sri Lakshmi Electricals & Hardware Partner',
      hubType: 'Merchant / Seller Partner Hub',
      phone: '+91 98450 11223',
      maskedPhone: '+91 98XXX-XX223 (QCOM Proxy)',
      address: 'Shop 14, 100 Feet Rd, HAL 2nd Stage, Indiranagar',
      locality: 'Indiranagar, Bengaluru',
      coordinates: { lat: 12.9784, lng: 77.6408 },
      basePrepMins: 4,
      isPacked: true,
    },
    drop: {
      customerName: 'Rahul Sharma (Site Engg)',
      customerPhone: '+91 98860 12345',
      maskedPhone: '+91 98XXX-XX345 (QCOM Proxy)',
      isPhoneMasked: true,
      accountType: 'contractor',
      businessName: 'Apex Infra Projects',
      address: 'Tower B, 4th Floor, Site 88, 12th Main Rd, Indiranagar',
      locality: 'Indiranagar, Bengaluru',
      siteContactName: 'Mahesh (Site Foreman)',
      sitePhone: '+91 98451 99887',
      coordinates: { lat: 12.9812, lng: 77.645 },
    },
    payoutBreakdown: {
      basePay: 35,
      distancePay: 32.8,
      transitTimePay: 6.5,
      surgeBonus: 0,
      multiPickupBonus: 0,
      customerTip: 50,
      totalPayout: 124.3,
    },
    route: {
      distanceMeters: 4100,
      distanceKm: 4.1,
      estimatedDurationMins: 13,
      formattedEta: '13 mins',
      polyline: [
        [12.9784, 77.6408],
        [12.9812, 77.645],
      ],
      instructions: [],
    },
    deliveryOtp: '4921',
    isUrgentJobsite: true,
    pickupProof: {
      id: 'PROOF-PICKUP-88191',
      photoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=700',
      timestamp: '22 Sep 2026, 08:35:12 AM',
      stage: 'PICKUP',
      coordinates: { lat: 12.9784, lng: 77.6408 },
      capturedByPartnerId: 'RIDER-4029',
      orderNumber: '#Q88191',
      tamperSealStatus: 'INTACT_VERIFIED',
      securityHash: 'SHA256:QC-78F91A20-B92104',
      retentionUntil: '2026-09-29T08:35:00.000Z',
      retentionDaysRemaining: 7,
      note: 'Store seal verified intact with package barcode attached at Indiranagar Store',
    },
    deliveryProof: {
      id: 'PROOF-DELIVERY-88191',
      photoUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=700',
      timestamp: '22 Sep 2026, 08:52:04 AM',
      stage: 'DELIVERY',
      coordinates: { lat: 12.9812, lng: 77.645 },
      capturedByPartnerId: 'RIDER-4029',
      orderNumber: '#Q88191',
      tamperSealStatus: 'INTACT_VERIFIED',
      securityHash: 'SHA256:QC-81B34091-E0491F',
      retentionUntil: '2026-09-29T08:52:00.000Z',
      retentionDaysRemaining: 7,
      note: 'Handed over directly to customer Rahul Sharma with OTP #4921 matched',
    },
  },
  {
    id: 'TASK-9018',
    orderId: 'ORD-88190',
    orderNumber: '#Q88190',
    orderStatus: 'delivered',
    placedAt: '2026-09-22T07:10:00.000Z',
    packedAt: '2026-09-22T07:18:00.000Z',
    assignedAt: '2026-09-22T07:19:00.000Z',
    acceptedAt: '2026-09-22T07:19:30.000Z',
    pickedUpAt: '2026-09-22T07:28:00.000Z',
    deliveredAt: '2026-09-22T07:44:00.000Z',
    estimatedDeliveryAt: '2026-09-22T07:45:00.000Z',
    items: [
      {
        productId: 'P-102',
        productName: '16A Modular Switch & Socket Combined',
        brand: 'Schneider Electric',
        quantity: 5,
        unit: 'Units',
        price: 260,
      },
    ],
    itemCount: 5,
    orderTotalAmount: 1300,
    paymentMethod: 'Instant UPI',
    paymentStatus: 'PAID',
    pickup: {
      sellerId: 'SEL-8819',
      storeName: 'Sri Lakshmi Electricals & Hardware Partner',
      hubType: 'Merchant / Seller Partner Hub',
      phone: '+91 98450 11223',
      maskedPhone: '+91 98XXX-XX223 (QCOM Proxy)',
      address: 'Shop 14, 100 Feet Rd, HAL 2nd Stage, Indiranagar',
      locality: 'Indiranagar, Bengaluru',
      coordinates: { lat: 12.9784, lng: 77.6408 },
      basePrepMins: 4,
      isPacked: true,
    },
    drop: {
      customerName: 'Kavita Menon',
      customerPhone: '+91 98860 44556',
      maskedPhone: '+91 98XXX-XX556 (QCOM Proxy)',
      isPhoneMasked: true,
      accountType: 'individual',
      address: 'Flat 304, Green Glen Apts, Domlur',
      locality: 'Domlur, Bengaluru',
      siteContactName: 'Kavita Menon',
      sitePhone: '+91 98860 44556',
      coordinates: { lat: 12.9609, lng: 77.6387 },
    },
    payoutBreakdown: {
      basePay: 35,
      distancePay: 20,
      transitTimePay: 5,
      surgeBonus: 10,
      multiPickupBonus: 0,
      customerTip: 25,
      totalPayout: 95,
    },
    route: {
      distanceMeters: 2500,
      distanceKm: 2.5,
      estimatedDurationMins: 11,
      formattedEta: '11 mins',
      polyline: [],
      instructions: [],
    },
    deliveryOtp: '8204',
    isUrgentJobsite: false,
    pickupProof: {
      id: 'PROOF-PICKUP-88190',
      photoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=700',
      timestamp: '22 Sep 2026, 07:28:10 AM',
      stage: 'PICKUP',
      coordinates: { lat: 12.9784, lng: 77.6408 },
      capturedByPartnerId: 'RIDER-4029',
      orderNumber: '#Q88190',
      tamperSealStatus: 'INTACT_VERIFIED',
      securityHash: 'SHA256:QC-55A12E80-9910DF',
      retentionUntil: '2026-09-29T07:28:00.000Z',
      retentionDaysRemaining: 7,
      note: 'Tamper-evident seal verified with store counter staff',
    },
    deliveryProof: {
      id: 'PROOF-DELIVERY-88190',
      photoUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&q=80&w=700',
      timestamp: '22 Sep 2026, 07:44:18 AM',
      stage: 'DELIVERY',
      coordinates: { lat: 12.9609, lng: 77.6387 },
      capturedByPartnerId: 'RIDER-4029',
      orderNumber: '#Q88190',
      tamperSealStatus: 'INTACT_VERIFIED',
      securityHash: 'SHA256:QC-99C12048-A8108B',
      retentionUntil: '2026-09-29T07:44:00.000Z',
      retentionDaysRemaining: 7,
      note: 'Delivered at flat 304 doorstep, customer OTP verified',
    },
  },
];

export const INITIAL_EARNINGS_SUMMARY: PartnerEarningsSummary = {
  todayTotalEarnings: 948,
  todayTripsCompleted: 8,
  todayBasePayTotal: 748,
  todayIncentivesTotal: 130,
  todayTipsTotal: 70,
  todayOnlineMinutes: 310,
  pendingWithdrawableBalance: 2410,
  settledLifetimeEarnings: 38450,
  nextPayoutDate: 'Tomorrow, 08:00 AM (Auto-UPI Release)',
  avgEarningsPerTrip: 118.5,
};

export const INITIAL_RIDER_LEDGER: RiderLedgerEntry[] = [
  {
    id: 'LEDGER-101',
    riderId: 'RIDER-4029',
    date: '21 Sep 2026',
    timestamp: '11:42 AM',
    type: 'TRIP_EARNING',
    category: 'CREDIT',
    title: 'Trip Payout - #Q88191',
    description: 'Base Pay ₹35 + Distance (4.1km) ₹32.8 + Transit ₹6.5',
    amount: 74.3,
    orderNumber: '#Q88191',
    status: 'CLEARED',
  },
  {
    id: 'LEDGER-102',
    riderId: 'RIDER-4029',
    date: '21 Sep 2026',
    timestamp: '11:42 AM',
    type: 'CUSTOMER_TIP',
    category: 'CREDIT',
    title: 'Customer Tip - #Q88191',
    description: 'Direct 100% tip from Rahul S. (Apex Infra)',
    amount: 50.0,
    orderNumber: '#Q88191',
    status: 'CLEARED',
  },
  {
    id: 'LEDGER-103',
    riderId: 'RIDER-4029',
    date: '21 Sep 2026',
    timestamp: '11:00 AM',
    type: 'RAIN_PEAK_BONUS',
    category: 'CREDIT',
    title: 'Monsoon High-Demand Peak Surge',
    description: 'Operational peak bonus (Bengaluru East Zone)',
    amount: 45.0,
    status: 'CLEARED',
  },
  {
    id: 'LEDGER-104',
    riderId: 'RIDER-4029',
    date: '20 Sep 2026',
    timestamp: '08:00 PM',
    type: 'PAYOUT_RELEASE',
    category: 'DEBIT',
    title: 'Bank Settlement Release (NEFT/UPI)',
    description: 'Automated daily payout to HDFC A/C ****128 (UTR: HDFC948102948)',
    amount: 1820.0,
    status: 'RELEASED',
    payoutMode: 'UPI',
    utrNumber: 'HDFC948102948',
    releasedAt: '20 Sep 2026 08:05 PM',
  },
];

export const INITIAL_NOTIFICATIONS: PartnerNotification[] = [
  {
    id: 'NOTIF-01',
    type: 'NEW_TASK_BROADCAST',
    title: 'High Earnings Delivery Alert',
    message: 'New Urgent Hardware delivery near Koramangala. Earn ₹97 for 2.8 km.',
    timestamp: '2 mins ago',
    isRead: false,
    priority: 'HIGH',
    taskId: 'TASK-9022',
  },
  {
    id: 'NOTIF-02',
    type: 'BATTERY_LOW',
    title: 'Battery Range Reminder',
    message: 'Your EV Scooter is at 84% battery (~72 km range remaining). Good for ~18 trips.',
    timestamp: '1 hour ago',
    isRead: true,
    priority: 'NORMAL',
  },
  {
    id: 'NOTIF-03',
    type: 'PAYOUT_RELEASED',
    title: 'Daily Payout Processed',
    message: '₹1,820 credited to your HDFC Bank account via UPI (UTR: HDFC948102948).',
    timestamp: 'Yesterday',
    isRead: true,
    priority: 'NORMAL',
  },
];

export const INITIAL_SHIFT_SLOTS: ShiftSlot[] = [
  // ----------------------------------------------------
  // DAY 1: Mon, 22 Sep (Today) - Operating Hours: 08:00 AM – 08:00 PM
  // ----------------------------------------------------
  {
    id: 'SHIFT-201',
    hubId: 'HUB-INDIRANAGAR',
    zoneName: 'Indiranagar Zone',
    shiftType: 'MORNING_PEAK',
    shiftName: 'Morning Contractor & Site Rush',
    dateStr: '2026-09-22',
    dayLabel: 'Mon, 22 Sep (Today)',
    startTime: '08:00 AM',
    endTime: '11:00 AM',
    capacityLimit: 40,
    bookedCount: 40,
    minEarningsGuarantee: 360,
    status: 'FILLED',
    tierAccessRequired: 'BRONZE',
    spotSurgeMultiplier: 1.25,
    isPeakBonusEligible: true,
  },
  {
    id: 'SHIFT-202',
    hubId: 'HUB-INDIRANAGAR',
    zoneName: 'Indiranagar Zone',
    shiftType: 'MIDDAY_PEAK',
    shiftName: 'Midday Workshop & Garage Peak',
    dateStr: '2026-09-22',
    dayLabel: 'Mon, 22 Sep (Today)',
    startTime: '11:00 AM',
    endTime: '02:00 PM',
    capacityLimit: 50,
    bookedCount: 42,
    minEarningsGuarantee: 450,
    status: 'BOOKED',
    tierAccessRequired: 'BRONZE',
    spotSurgeMultiplier: 1.35,
    isPeakBonusEligible: true,
  },
  {
    id: 'SHIFT-203',
    hubId: 'HUB-INDIRANAGAR',
    zoneName: 'Indiranagar Zone',
    shiftType: 'AFTERNOON_SLOT',
    shiftName: 'Afternoon Hardware & Spares Run',
    dateStr: '2026-09-22',
    dayLabel: 'Mon, 22 Sep (Today)',
    startTime: '02:00 PM',
    endTime: '05:00 PM',
    capacityLimit: 35,
    bookedCount: 20,
    minEarningsGuarantee: 380,
    status: 'AVAILABLE',
    tierAccessRequired: 'BRONZE',
    spotSurgeMultiplier: 1.2,
    isPeakBonusEligible: false,
  },
  {
    id: 'SHIFT-204',
    hubId: 'HUB-INDIRANAGAR',
    zoneName: 'Indiranagar Zone',
    shiftType: 'EVENING_SLOT',
    shiftName: 'Evening Wind-Down & Site Wrap-Up',
    dateStr: '2026-09-22',
    dayLabel: 'Mon, 22 Sep (Today)',
    startTime: '05:00 PM',
    endTime: '08:00 PM',
    capacityLimit: 60,
    bookedCount: 38,
    minEarningsGuarantee: 320,
    status: 'AVAILABLE',
    tierAccessRequired: 'BRONZE',
    spotSurgeMultiplier: 1.0,
    isPeakBonusEligible: false,
  },

  // ----------------------------------------------------
  // DAY 2: Tue, 23 Sep - Operating Hours: 08:00 AM – 08:00 PM
  // ----------------------------------------------------
  {
    id: 'SHIFT-205',
    hubId: 'HUB-KORAMANGALA',
    zoneName: 'Koramangala Zone',
    shiftType: 'MORNING_PEAK',
    shiftName: 'Morning Plumbing & Electrical Rush',
    dateStr: '2026-09-23',
    dayLabel: 'Tue, 23 Sep',
    startTime: '08:00 AM',
    endTime: '11:00 AM',
    capacityLimit: 35,
    bookedCount: 15,
    minEarningsGuarantee: 360,
    status: 'AVAILABLE',
    tierAccessRequired: 'BRONZE',
    spotSurgeMultiplier: 1.2,
    isPeakBonusEligible: true,
  },
  {
    id: 'SHIFT-206',
    hubId: 'HUB-KORAMANGALA',
    zoneName: 'Koramangala Zone',
    shiftType: 'MIDDAY_PEAK',
    shiftName: 'Koramangala Auto Spares Peak',
    dateStr: '2026-09-23',
    dayLabel: 'Tue, 23 Sep',
    startTime: '11:00 AM',
    endTime: '02:00 PM',
    capacityLimit: 45,
    bookedCount: 30,
    minEarningsGuarantee: 450,
    status: 'AVAILABLE',
    tierAccessRequired: 'BRONZE',
    spotSurgeMultiplier: 1.3,
    isPeakBonusEligible: true,
  },
  {
    id: 'SHIFT-207',
    hubId: 'HUB-KORAMANGALA',
    zoneName: 'Koramangala Zone',
    shiftType: 'AFTERNOON_SLOT',
    shiftName: 'Carpentry & Fasteners Express Slot',
    dateStr: '2026-09-23',
    dayLabel: 'Tue, 23 Sep',
    startTime: '02:00 PM',
    endTime: '05:00 PM',
    capacityLimit: 30,
    bookedCount: 12,
    minEarningsGuarantee: 380,
    status: 'AVAILABLE',
    tierAccessRequired: 'BRONZE',
    spotSurgeMultiplier: 1.15,
    isPeakBonusEligible: false,
  },
  {
    id: 'SHIFT-208',
    hubId: 'HUB-KORAMANGALA',
    zoneName: 'Koramangala Zone',
    shiftType: 'EVENING_SLOT',
    shiftName: 'Evening Wind-Down & Site Wrap-Up',
    dateStr: '2026-09-23',
    dayLabel: 'Tue, 23 Sep',
    startTime: '05:00 PM',
    endTime: '08:00 PM',
    capacityLimit: 55,
    bookedCount: 22,
    minEarningsGuarantee: 320,
    status: 'AVAILABLE',
    tierAccessRequired: 'BRONZE',
    spotSurgeMultiplier: 1.0,
    isPeakBonusEligible: false,
  },

  // ----------------------------------------------------
  // DAY 3: Wed, 24 Sep - Operating Hours: 08:00 AM – 08:00 PM
  // ----------------------------------------------------
  {
    id: 'SHIFT-209',
    hubId: 'HUB-HSR',
    zoneName: 'HSR Layout Zone',
    shiftType: 'MORNING_PEAK',
    shiftName: 'HSR Morning Jobsite Rush',
    dateStr: '2026-09-24',
    dayLabel: 'Wed, 24 Sep',
    startTime: '08:00 AM',
    endTime: '11:00 AM',
    capacityLimit: 40,
    bookedCount: 18,
    minEarningsGuarantee: 370,
    status: 'AVAILABLE',
    tierAccessRequired: 'BRONZE',
    spotSurgeMultiplier: 1.25,
    isPeakBonusEligible: true,
  },
  {
    id: 'SHIFT-210',
    hubId: 'HUB-HSR',
    zoneName: 'HSR Layout Zone',
    shiftType: 'MIDDAY_PEAK',
    shiftName: 'HSR Garage Spares Midday Peak',
    dateStr: '2026-09-24',
    dayLabel: 'Wed, 24 Sep',
    startTime: '11:00 AM',
    endTime: '02:00 PM',
    capacityLimit: 45,
    bookedCount: 24,
    minEarningsGuarantee: 460,
    status: 'AVAILABLE',
    tierAccessRequired: 'BRONZE',
    spotSurgeMultiplier: 1.35,
    isPeakBonusEligible: true,
  },
  {
    id: 'SHIFT-211',
    hubId: 'HUB-HSR',
    zoneName: 'HSR Layout Zone',
    shiftType: 'AFTERNOON_SLOT',
    shiftName: 'HSR Hardware & Pipe Dispatch',
    dateStr: '2026-09-24',
    dayLabel: 'Wed, 24 Sep',
    startTime: '02:00 PM',
    endTime: '05:00 PM',
    capacityLimit: 30,
    bookedCount: 10,
    minEarningsGuarantee: 380,
    status: 'AVAILABLE',
    tierAccessRequired: 'SILVER',
    spotSurgeMultiplier: 1.2,
    isPeakBonusEligible: false,
  },
  {
    id: 'SHIFT-212',
    hubId: 'HUB-HSR',
    zoneName: 'HSR Layout Zone',
    shiftType: 'EVENING_SLOT',
    shiftName: 'HSR Evening Wind-Down Slot',
    dateStr: '2026-09-24',
    dayLabel: 'Wed, 24 Sep',
    startTime: '05:00 PM',
    endTime: '08:00 PM',
    capacityLimit: 50,
    bookedCount: 14,
    minEarningsGuarantee: 320,
    status: 'AVAILABLE',
    tierAccessRequired: 'GOLD',
    spotSurgeMultiplier: 1.0,
    isPeakBonusEligible: false,
  },

  // ----------------------------------------------------
  // DAY 4: Thu, 25 Sep - Operating Hours: 08:00 AM – 08:00 PM
  // ----------------------------------------------------
  {
    id: 'SHIFT-213',
    hubId: 'HUB-INDIRANAGAR',
    zoneName: 'Indiranagar Zone',
    shiftType: 'MORNING_PEAK',
    shiftName: 'Thursday Trade & Hardware Window',
    dateStr: '2026-09-25',
    dayLabel: 'Thu, 25 Sep',
    startTime: '08:00 AM',
    endTime: '11:00 AM',
    capacityLimit: 40,
    bookedCount: 20,
    minEarningsGuarantee: 360,
    status: 'AVAILABLE',
    tierAccessRequired: 'BRONZE',
    spotSurgeMultiplier: 1.2,
    isPeakBonusEligible: true,
  },
  {
    id: 'SHIFT-214',
    hubId: 'HUB-INDIRANAGAR',
    zoneName: 'Indiranagar Zone',
    shiftType: 'MIDDAY_PEAK',
    shiftName: 'Thursday Auto Parts Rush',
    dateStr: '2026-09-25',
    dayLabel: 'Thu, 25 Sep',
    startTime: '11:00 AM',
    endTime: '02:00 PM',
    capacityLimit: 50,
    bookedCount: 30,
    minEarningsGuarantee: 450,
    status: 'AVAILABLE',
    tierAccessRequired: 'BRONZE',
    spotSurgeMultiplier: 1.3,
    isPeakBonusEligible: true,
  },
  {
    id: 'SHIFT-215',
    hubId: 'HUB-INDIRANAGAR',
    zoneName: 'Indiranagar Zone',
    shiftType: 'AFTERNOON_SLOT',
    shiftName: 'Thursday Midday Dispatch',
    dateStr: '2026-09-25',
    dayLabel: 'Thu, 25 Sep',
    startTime: '02:00 PM',
    endTime: '05:00 PM',
    capacityLimit: 35,
    bookedCount: 15,
    minEarningsGuarantee: 380,
    status: 'AVAILABLE',
    tierAccessRequired: 'BRONZE',
    spotSurgeMultiplier: 1.2,
    isPeakBonusEligible: false,
  },
  {
    id: 'SHIFT-216',
    hubId: 'HUB-INDIRANAGAR',
    zoneName: 'Indiranagar Zone',
    shiftType: 'EVENING_SLOT',
    shiftName: 'Thursday Evening Wind-Down Slot',
    dateStr: '2026-09-25',
    dayLabel: 'Thu, 25 Sep',
    startTime: '05:00 PM',
    endTime: '08:00 PM',
    capacityLimit: 60,
    bookedCount: 28,
    minEarningsGuarantee: 320,
    status: 'AVAILABLE',
    tierAccessRequired: 'SILVER',
    spotSurgeMultiplier: 1.0,
    isPeakBonusEligible: false,
  },

  // ----------------------------------------------------
  // DAY 5: Fri, 26 Sep - Operating Hours: 08:00 AM – 08:00 PM
  // ----------------------------------------------------
  {
    id: 'SHIFT-217',
    hubId: 'HUB-INDIRANAGAR',
    zoneName: 'Indiranagar Zone',
    shiftType: 'MORNING_PEAK',
    shiftName: 'Friday Morning Tools & Spares',
    dateStr: '2026-09-26',
    dayLabel: 'Fri, 26 Sep',
    startTime: '08:00 AM',
    endTime: '11:00 AM',
    capacityLimit: 45,
    bookedCount: 22,
    minEarningsGuarantee: 380,
    status: 'AVAILABLE',
    tierAccessRequired: 'BRONZE',
    spotSurgeMultiplier: 1.25,
    isPeakBonusEligible: true,
  },
  {
    id: 'SHIFT-218',
    hubId: 'HUB-INDIRANAGAR',
    zoneName: 'Indiranagar Zone',
    shiftType: 'MIDDAY_PEAK',
    shiftName: 'Friday Workshop High Demand',
    dateStr: '2026-09-26',
    dayLabel: 'Fri, 26 Sep',
    startTime: '11:00 AM',
    endTime: '02:00 PM',
    capacityLimit: 55,
    bookedCount: 35,
    minEarningsGuarantee: 480,
    status: 'AVAILABLE',
    tierAccessRequired: 'BRONZE',
    spotSurgeMultiplier: 1.4,
    isPeakBonusEligible: true,
  },
  {
    id: 'SHIFT-219',
    hubId: 'HUB-INDIRANAGAR',
    zoneName: 'Indiranagar Zone',
    shiftType: 'AFTERNOON_SLOT',
    shiftName: 'Friday Pre-Weekend Spares Run',
    dateStr: '2026-09-26',
    dayLabel: 'Fri, 26 Sep',
    startTime: '02:00 PM',
    endTime: '05:00 PM',
    capacityLimit: 40,
    bookedCount: 18,
    minEarningsGuarantee: 400,
    status: 'AVAILABLE',
    tierAccessRequired: 'BRONZE',
    spotSurgeMultiplier: 1.25,
    isPeakBonusEligible: true,
  },
  {
    id: 'SHIFT-220',
    hubId: 'HUB-INDIRANAGAR',
    zoneName: 'Indiranagar Zone',
    shiftType: 'EVENING_SLOT',
    shiftName: 'Friday Evening Wind-Down & Closure',
    dateStr: '2026-09-26',
    dayLabel: 'Fri, 26 Sep',
    startTime: '05:00 PM',
    endTime: '08:00 PM',
    capacityLimit: 80,
    bookedCount: 12,
    minEarningsGuarantee: 350,
    status: 'LOCKED',
    tierAccessRequired: 'PLATINUM',
    spotSurgeMultiplier: 1.0,
    isPeakBonusEligible: false,
  },
];

export const INITIAL_KYC_DOCUMENTS: KycDocumentDetail[] = [
  {
    id: 'DOC-01',
    type: 'AADHAAR',
    name: 'Aadhaar Identity Card',
    documentNumber: 'XXXX-XXXX-4819',
    status: 'VERIFIED',
    verifiedVia: 'Digilocker e-KYC (UIDAI OTP)',
    verifiedAt: '12 Jan 2025',
  },
  {
    id: 'DOC-02',
    type: 'PAN',
    name: 'Permanent Account Number (PAN)',
    documentNumber: 'BNXPS****D',
    status: 'VERIFIED',
    verifiedVia: 'NSDL Income Tax Department API',
    verifiedAt: '12 Jan 2025',
  },
  {
    id: 'DOC-03',
    type: 'DRIVING_LICENSE',
    name: 'Motor Vehicle Driving License (MCWG)',
    documentNumber: 'KA-03-2018-0049210',
    status: 'VERIFIED',
    verifiedVia: 'Parivahan Sarathi API Registry',
    verifiedAt: '14 Jan 2025',
    expiryDate: '15 Aug 2038',
  },
  {
    id: 'DOC-04',
    type: 'VEHICLE_RC',
    name: 'Vehicle Registration Certificate (RC)',
    documentNumber: 'KA 03 EV 8821',
    status: 'VERIFIED',
    verifiedVia: 'Vahan National Vehicle Registry',
    verifiedAt: '14 Jan 2025',
    expiryDate: '10 Nov 2035',
  },
  {
    id: 'DOC-05',
    type: 'BANK_PENNY_DROP',
    name: 'IMPS Bank Penny-Drop Name Match',
    documentNumber: 'HDFC Bank - A/C 9182371900128',
    status: 'VERIFIED',
    verifiedVia: 'RazorpayX Penny-Drop (Score: 0.96)',
    verifiedAt: '15 Jan 2025',
  },
];

export const VEHICLE_CONSTRAINTS: VehicleConstraint[] = [
  {
    vehicleType: 'BICYCLE',
    label: 'Standard / Electric Bicycle',
    maxRadiusKm: 2.5,
    maxWeightKg: 5,
    allowedOrderTypes: ['Small Fasteners & Screws', 'Spark Plugs & Relays', 'Modular Switches & Sockets', 'Plumbing Teflon Tapes & Washers'],
    batteryRequired: false,
  },
  {
    vehicleType: 'EV_SCOOTER',
    label: 'Electric 2-Wheeler (EV)',
    maxRadiusKm: 6.0,
    maxWeightKg: 15,
    allowedOrderTypes: ['Power Tools & Drill Kits', 'Electrical Cable Coils', 'Bath & Kitchen Fittings', 'Motorcycle / Scooter Spare Parts'],
    batteryRequired: true,
  },
  {
    vehicleType: 'PETROL_SCOOTER',
    label: 'Motorcycle / ICE Scooter',
    maxRadiusKm: 10.0,
    maxWeightKg: 25,
    allowedOrderTypes: ['Car Brake Discs & Rotors', 'Engine Oil Drums (1-5L)', 'Sanitaryware & Basin Mixers', 'Carpentry Adhesives & Sanders'],
    batteryRequired: false,
  },
  {
    vehicleType: 'E_CARGO_3W',
    label: 'Electric Cargo 3-Wheeler',
    maxRadiusKm: 18.0,
    maxWeightKg: 120,
    allowedOrderTypes: ['CPVC / PVC Pipe Bundles', 'Car & Inverter Batteries', 'Submersible Pumps', 'Bulk Commercial Pallets'],
    batteryRequired: true,
  },
];

export const INITIAL_ASSET_ALLOCATIONS: AssetAllocation[] = [
  {
    id: 'ASSET-01',
    assetType: 'DELIVERY_BAG',
    name: 'Heavy-Duty Reinforced Tool & Spares Delivery Bag (45L)',
    serialNumber: 'BAG-QCOM-BLR-0941',
    qrCode: 'QCOM-BAG-0941-VERIFIED',
    assignedAt: '16 Jan 2025',
    status: 'ASSIGNED',
  },
  {
    id: 'ASSET-02',
    assetType: 'RAIN_JACKET',
    name: 'High-Visibility Neon Waterproof Riding Jacket',
    serialNumber: 'JKT-QCOM-BLR-1822',
    qrCode: 'QCOM-JKT-1822-VERIFIED',
    assignedAt: '16 Jan 2025',
    status: 'ASSIGNED',
  },
  {
    id: 'ASSET-03',
    assetType: 'HELMET_SAFETY_KIT',
    name: 'DOT/ISI Certified Aerodynamic Full Helmet',
    serialNumber: 'HLM-QCOM-BLR-3301',
    qrCode: 'QCOM-HLM-3301-VERIFIED',
    assignedAt: '16 Jan 2025',
    status: 'ASSIGNED',
  },
];

export const INITIAL_SAFETY_MODULES: SafetyTrainingModule[] = [
  {
    id: 'MOD-01',
    title: 'Heavy Hardware & Automotive Fluids Handling Protocol',
    category: 'HARDWARE_HANDLING',
    durationMinutes: 4,
    isCompleted: true,
    scorePercent: 100,
    completedAt: '16 Jan 2025',
  },
  {
    id: 'MOD-02',
    title: 'Defensive Two-Wheeler Riding with Heavy Tools & Spares',
    category: 'SAFETY',
    durationMinutes: 5,
    isCompleted: true,
    scorePercent: 95,
    completedAt: '16 Jan 2025',
  },
  {
    id: 'MOD-03',
    title: 'Jobsite Delivery & Workshop Handover Protocol',
    category: 'CUSTOMER_ETIQUETTE',
    durationMinutes: 3,
    isCompleted: true,
    scorePercent: 100,
    completedAt: '17 Jan 2025',
  },
];

export const INITIAL_PERFORMANCE_SCORECARD: PerformanceScorecard = {
  tier: 'PLATINUM',
  acceptanceRatePercent: 96.5,
  completionRatePercent: 99.2,
  onTimeDeliveryRatePercent: 98.4,
  customerRating: 4.92,
  totalTripsCompleted: 418,
  unlockedPerks: [
    '72-Hour Priority Shift Slot Access',
    'Sub-2 Second VIP Dispatch Priority on High-Payout Orders',
    '0% Convenience Fee on Instant UPI Payout Withdrawals',
    'Increased Floating Cash Ceiling up to ₹3,500',
    'Dedicated 24/7 Priority Courier Telephony Helpdesk',
  ],
};
